title       = "vietnamtravel"
baseURL     = "https://vietnamtravel-cli.tamnd.com/"
description = "A command line for vietnamtravel."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/vietnamtravel-cli"
